### ISSUE TITLE
ScrollView无法返回Header

### ISSUE THREAD

**Issue by xxxifan** [cpoopc/ScrollableLayout#1]
首先感谢作者分享这个开源库，把我一天甚至更长时间的工作缩短为了10分钟

我在用的时候遇到了一个问题，我有两个fragment，一个是scrollView的，一个是ListView，在ScrollView这边下滑到Header看不到之后，再往上滑就只能滑到ScrollView的顶部，看不到Header了，而ListView则是正常的，调试找到Action_Move里面的这里

    if (shiftY > mTouchSlop && shiftY > shiftX && (!isSticked() || mHelper.isTop() || isClickHeadExpand)) {
                    deltaY = deltaY * 9 / 10;
                    scrollBy(0, (int) deltaY);
                }

是没有执行进去的，不知道是何原因，请求帮助

**Comment by xxxifan** [comment]
是不是mHelper.isTop()不支持ScrollView导致的？刚刚找到了这里  还不确定

**Comment by xxxifan** [comment]
确定这个跟这个问题有关，现在可以滑了  但是滑到一半会停下来

**Comment by cpoopc** [comment]
@xxxifan 不好意思啊,刚看到问题
我添加了对ScrollView的支持,和demo,你可以更新一下
PS:需要拓展其他view,可以重写ScrollableHelper.isTop()方法

**Comment by xxxifan** [comment]
好的  问题解决了

另外还有两个问题
  1是显示header的时候向下滑   会触发ViewPager翻页，当header不显示的时候就不会了
2是快速滑动的时候动画很奇怪，会立刻到达顶部/底部

**Comment by cpoopc** [comment]
第一个问题没看明白..
第二个是指fling的时候Scrollview滑动的太快了吗?

**Comment by xxxifan** [comment]
有空给您做个视频吧  确实很抽象不好描述

**Comment by xxxifan** [comment]
http://pan.baidu.com/s/1dDJd8D7
前面 是问题1    后面是问题2，滑动可能有点看不出来  - -

**Comment by cpoopc** [comment]
视频看到了
问题1是不是你的操作是不是斜着划了?
问题2我改好了,你可以再更新试试,

**Comment by xxxifan** [comment]
问题一是有斜着划  但是是在先触发垂直滚动的前提下   就是说现在垂直滚动跟横向滚动被同时触发了

**Comment by cpoopc** [comment]
我又优化了下,试试有没有解决了
