### ISSUE TITLE
View doesn`t return

### ISSUE THREAD

**Issue by ppamorim** [cpoopc/ScrollableLayout#2]
When I scroll, the top view don\`t returns when I push it again. I`m using a simple layout, like:

     - ScrollableLayout
       - RelativeLayout\
       - RecyclerView\
     - \ScrollableLayout

My fragment implements ```ScrollableHelper.ScrollableContainer``` and I uses ```scrollableLayout.getHelper().setCurrentScrollableContainer(this);``` to set the listener.

I don`t know whats happening.

**Comment by cpoopc** [comment]
i guess you implements ScrollableHelper.ScrollableContainer with wrong way like below?
```
    @Override
    public View getScrollableView() {
        return null;
    }
```
but it should be 
```
    @Override
    public View getScrollableView() {
        return mRecyclerView;// RecyclerView instance
    }
```
am i guess right?

**Comment by ppamorim** [comment]
@cpoopc I think that getScrollableView wants the RelativeLayout. By the way... Can you add a validator to this? Just:
```java
if(!scrollableView instanceof RecyclerView...[n]) {
    throw new IllegalStateException("scrollableView must be a instance of list");
}
```

**Comment by cpoopc** [comment]
@ppamorim ok,i have add it.  :)
