### ISSUE TITLE
Scroll Listener / parallax

### ISSUE THREAD

**Issue by FunnyDevs** [cpoopc/ScrollableLayout#3]
Hi! I would like to implement parallax scrolling on the header. Is possibile to have a scroll listener??? Thanks!!

**Comment by cpoopc** [comment]
i add scroll listener to support parallax into ParallaxSupport branch.
just try it

**Comment by FunnyDevs** [comment]
@cpoopc Thanks a lot! Your library is perfect! Better than others (and even of the new CoordinatorLayout of Support Design Lib)
