### ISSUE TITLE
向上滑动后头就没有了

### ISSUE THREAD

**Issue by MakerYan** [cpoopc/ScrollableLayout#5]
向上滑动后头就没有了, 头像吞噬掉了,滑动一点吞噬一点

**Comment by cpoopc** [comment]
你需要
1.实现ScrollableHelper.ScrollableContainer接口的getScrollableView()方法,getScrollableView()方法返回嵌套滚动的View(比如ListView,RecyclerView)
2.将其传递给ScrollableLayout
mScrollLayout.getHelper().setCurrentScrollableContainer(scrollableContainer)

**Comment by MakerYan** [comment]
谢谢，已解决！ 发自网易邮箱大师 在2016年03月11日 11:27 ，cpoopc写道： 你需要 1.实现ScrollableHelper.ScrollableContainer接口的getScrollableView()方法,getScrollableView()方法返回嵌套滚动的View(比如ListView,RecyclerView) 2.将其传递给ScrollableLayout mScrollLayout.getHelper().setCurrentScrollableContainer(scrollableContainer) — Reply to this email directly or view it on GitHub.

**Comment by MakerYan** [comment]
你好，现在遇到新问题了，下拉刷新成功一次之后只要吧头推上去就拉不下来了，也不能刷新了 发自网易邮箱大师 在2016年03月11日 12:47 ，cpoopc写道： Closed #5. — Reply to this email directly or view it on GitHub.

**Comment by cpoopc** [comment]
跟下拉刷新没有关系吧.下拉刷新做了什么操作?排查下你操作的内存对象是不是界面显示的对象

**Comment by MakerYan** [comment]
修改了一下你的源码问题解决了，谢谢！ 发自网易邮箱大师 在2016年03月14日 10:06 ，cpoopc写道： 跟下拉刷新没有关系吧.下拉刷新做了什么操作?排查下你操作的内存对象是不是界面显示的对象 — Reply to this email directly or view it on GitHub.

**Comment by cpoopc** [comment]
是什么问题导致的呢?

**Comment by MakerYan** [comment]
listview和GridView应该是没问题，我用的是recyclerview，ScrollableHelper里面的isRecyclerViewTop方法判断好像有问题，我改了一下就好了。 刚才我带了附件，系统给我返回来了， 发自网易邮箱大师 在2016年03月14日 10:11 ，cpoopc写道： 是什么问题导致的呢? — Reply to this email directly or view it on GitHub.
